Node.js (TypeScript) 実装の追加
showwin/ISHOCON1 pull request #19
Opened 2021-02-02 09:42 UTC by astj

こんにちは！度々お世話になっています。

先日株式会社はてなで社内 ISUCON を開催し、その際に ISHOCON1 を課題として利用させていただきました。ありがとうございました！
（追って社のブログとかでその話を公開するかとは思います。一旦ご挨拶まで）

その際に参加者からのリクエストで Node.js 実装 (TypeScript) を新たに追加しました。今後開催される方の助けになるかとも思いましたので p-r させていただきます！

他の言語での参考実装と同様に動作してベンチマークスコアもおおむね同程度でした。
はてな社内の社内 ISUCON で利用した実績もあるので、この状態で初期実装として利用可能だと考えています。

## 補足: Node.js 処理系の用意

用意されている AMI には Node.js の処理系が存在しなかったため、 https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions をもとに Node.js 14.x をセットアップして `sudo apt-get install -y nodejs` で導入して利用しました

2021-02-02 09:49 UTC, astj commented on webapp/nodejs/tsconfig.json
> +    "strict": true,
tsconfig は初期実装を書くときの都合で strict めに設定していますが、競技者がアプリケーションを書き替えるにはすこし窮屈かも？とは思っています

2021-02-02 09:49 UTC, astj commented on doc/manual.md
> +# TypeScript で書かれています
TypeScript ではない素の js を書きたい人は ~/webapp/nodejs/dist/ 以下に生成される js を編集する (+ そういう感じに package.json とかを調整してほしい) と思っていて、そのへん言及した方がいいのかなどうしようかなと思って書かないままにしています。書いた方がよければもうちょっと考えます！という感じです

2021-02-02 12:52 UTC, showwin requested changes
社内ISUCONで使って頂けたとのこと大変嬉しいです :smile: 
もしブログ記事書かれるようでしたら、READMEにもぜひ記載したいと思いますので、その際にはご教示頂けたら幸いです！

細かなところも含めていくつかコメントさせていただきました！
一部修正をお願いいたします :bow:

2021-02-02 12:52 UTC, showwin commented on doc/manual.md
> +#### Node.js (TypeSript) の場合
typoが…！！
```suggestion
#### Node.js (TypeScript) の場合
```

2021-02-02 12:52 UTC, showwin commented on doc/manual.md
> +# TypeScript で書かれています
良いですね！ありがとうございます。

```
TypeScript ではない素の JavaScript を書きたい方は ~/webapp/nodejs/dist/ 以下に生成される JS を編集し、また package.json 等もそれに合わせて調整いただくのがオススメです。
```
という感じの説明を起動コマンドの下辺りに書いておくのが良さそうですね！

2021-02-02 12:52 UTC, showwin commented on webapp/nodejs/tsconfig.json
> +    "strict": true,
必要に応じて競技者が変更するで良いと思うので、このままで大丈夫だと思います！

2021-02-02 12:52 UTC, showwin commented on webapp/nodejs/src/index.ts
> +      })) as Product["comments"];
(もしかしたら一部の言語実装でこうなっていたかもしれないですが) Ruby や Python 実装を見ると、コメントの件数が0件の時にもコメントを取りに行くクエリを投げていたと思うので、こちらの if 文は削除頂けると嬉しいです！

Pythonの例: https://github.com/showwin/ISHOCON1/blob/master/webapp/python/app.py#L177

2021-02-05 09:56 UTC, astj commented on webapp/nodejs/src/index.ts
> +      })) as Product["comments"];
[Go 実装](https://github.com/showwin/ISHOCON1/blob/master/webapp/go/product.go#L65) を参考に実装していてこうなっていました。
https://github.com/showwin/ISHOCON1/pull/19/commits/880cab1cb7558a7b7e5f3f056e350aca3012cd4e で削除しました！

2021-02-05 09:57 UTC, astj commented on doc/manual.md
> +# TypeScript で書かれています
提案いただいた内容とは少し雰囲気を変えてしまいましたが、こういう感じでいかがでしょうか https://github.com/showwin/ISHOCON1/pull/19/commits/ad8e8e21a80028237731c5dde7760147f88f43fc

2021-02-05 09:58 UTC, astj commented
コメントいただいた箇所を変更しました。再度ご確認いただければと思います :pray:

2021-02-07 01:55 UTC, showwin commented on doc/manual.md
> +# TypeScript で書かれています
とてもわかりやすいです！！

2021-02-07 01:56 UTC, showwin commented on webapp/nodejs/src/index.ts
> +      })) as Product["comments"];
それは申し訳ございませんでした🙏
修正ありがとうございます！

2021-02-07 01:57 UTC, showwin approved these changes
参考実装の追加ありがとうございます🎉🎉
とても助かります！！

2021-02-07 01:57 UTC, merged

2021-03-12 05:11 UTC, astj commented
> （追って社のブログとかでその話を公開するかとは思います。一旦ご挨拶まで）

既にご覧いただいているようですが、本日 https://developer.hatenastaff.com/entry/2021/03/12/103000 にて開催報告を公開しました。改めて、この度はありがとうございました！